# baseURL = "https://example.org"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
paginate = 30

title = "I'm Dilip"
# theme = "haki"
[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "docs"


[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "repository"
    name = "Repository"
    url = "/repository/"
    weight = 12

  [[menu.main]]
    identifier = "snippets"
    name = "Snippets"
    url = "/snippets/"
    weight = 11


  [[menu.secondary]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.secondary]]
    identifier= "rss"
    url = "index.xml"
    name = " Rss"
    title = "Rss feeds"
    weight = 12

[params]
  author = "Dilip"
  description = "The Thinker"
  sitename = "Dilip Nirvana"
  github = "https://github.com/idlip"
  # twitter = "@"
  favicon = "/images/op-roger.jpg"
  mainSections = "posts"


[[params.repository]]
  name = "Nix Config"
  description = "Nixos config in literate org-mode"
  sourceLink = "https://github.com/idlip/d-nix.git"

[[params.repository]]
  name = "Shell Scripts"
  description = "Some cool shell scripts which are useful"
  sourceLink = "https://github.com/idlip/d-bin.git"


[[params.repository]]
  name = "Flakes"
  description = "Flake setup into Modules (Deprecated)"
  sourceLink = "https://github.com/idlip/d-flake.git"
  


[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
