# baseURL = "https://idlip.github.io"
languageCode = "en"
title = "Dilip's Log"
theme = "emacs"

copyright = "Copyright © 2023-2025, Dilip G; All rights reserved."

enableEmoji = true
enableInlineShortcodes = true

[pagination]
  pagerSize = 7

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "public"

[params]

  description = "Dilip's Log"

  favicon = "/images/op-roger.jpg"

  hasNoscriptNotice = true

  imgPath = "images"

  markupImgClass = ""

  titleSeparator = "|"

  [params.author]
    name         = "Dilip's Log"
    description  = "Nix-Org-Macs in FOSS"
    email = 'dilip@fossunited.org'

  [params.contact]

    autoComplete      = false
    messageMinLength  = 30

    subject = [ 'Just saying "hi"', "I know what you did last winter", "... Is that a sloth?", "お前はもう死んでいる。" ]

    [params.contact.placeholder]
      name    = "Foo Bar"
      email   = "foo_bar@gnu.org"
      subject = 'Just saying "hi"'
      message = "Hi there!"

  [params.search]
    enable = true
    maxResults = 15
    minLength = 2
    maxLength = 42

    placeholder = "Emacs"

  [params.style]
    isDark = true
    ignoreSystemSettings = false
    darkAccent   = "#54ff9f"
    lightAccent  = "#4f94cd"

    presets = [ "#7fc121", "#51b37c", "#d2b48c", "#fafad2", "#00ff7f", "#ffe4e1", "#e6e6fa", "#00bfff", "#cd8500" ]

    hasIconAsFootnoteReturnLink = true

    socialIsFlex = false

    hideAnchors = true

    useCustomChroma = true

    changeTransition = ".3s ease"

  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Please report if this page is missing. Just nudge to zororg@tilde.green"

  [params.social.centralized]
    email         = [ "dilip@fossunited.org" ]
    github        = [ "idlip" ]
    linkedin      = [ "dilip-g-29707727a" ]
    reddit        = [ "GolD_Lip" ]
    telegram      = [ "zororg" ]

  [params.social.decentralized]

    [params.social.decentralized.matrix]
      1 = [ "https://matrix.to/#/zororg:matrix.org", "matrix" ]
    [params.social.decentralized.bsky]
      1 = [ "https://bsky.app/profile/idlip.bsky.social", "bluesky" ]
    [params.social.decentralized.mastodon]
      1 = [ "https://fosstodon.org/@idlip", "mastodon" ]


[menu]

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 2
  url = "/posts/"

[[menu.main]]
  name = "Projects"
  weight = 3
  url = "/repo/"

[[menu.main]]
  name = "About"
  weight = 4
  url = "/about/"

[[menu.main]]
  name = " "
  weight = 5
  url = "index.xml"


[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
