#+TITLE: Just a newbie blogging

The Journey begins..

You know its fascinating to have a personal static website which is rich and valuable for others.

I went with Hugo and ox-hugo which is a match that exists only for Emacs (GOAT) to build the site.

I have forked the theme from [[https://rudra.dev]] , and adjusted colors to my liking.


I hope its a soothing experience for you to read!

*** Ideas - TODO
**** TODO On Window manager
  SCHEDULED: <2023-03-30 Thu 13:01>
+ Maybe about advantages
+ Uses and how it is efficient
+ Bad side

**** DONE Fdroid & Fossdroid
  CLOSED: [2023-05-17 Wed 19:16] SCHEDULED: <2023-03-31 Fri 17:12>
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2023-05-17 Wed 19:16]
  :END:

**** DONE Use org file for scss too
  CLOSED: [2023-07-28 Fri 13:26] SCHEDULED: <2023-03-30 Thu 13:38>
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2023-07-28 Fri 13:26]
  :END:

**** TODO Comprehensive post on Emacs android
SCHEDULED: <2023-07-31 Mon>
+ It has got better with termux integration. Its almost like desktop experience now.

**** TODO Maybe on Revealjs for presentation?

**** On Bioinfo R/python learning?
