#+title: Rss: the Internet

** RSS: The better Internet :snippets:news:internet:read:rss:

*** Cheesy Internet

I don't have to say this, the Internet is hella bloated.. Junks are everywhere, nobody knows that they read shit, they are watching shits whole time.

Just do a test, How many popups have you closed today, How many cookies (web) have you eaten, How many captchas did you solve, How many minutes did you wait to skip an ad just to watch a video... Even worse, ads sponsors are embedded within a video (So cruel and harsh world)
/It goes on/.

Internet and digital software's are getting so much bloated, people (normies) have forgotten Unix or say 'minimalism'. People are upgrading RAM like anything, 8GB ain't enough it-seems for them. Here, I do everything with just 4GB RAM.
People these days all need ready-made/ready-to-work  stuffs, I wonder how do they even watch DIY channels on YouTube.

*** The Hero

Rss stands for *Really Simple Syndication*, It is a classic on consuming web as supposedly it was built for. Today its all crappy *JavaScript* (a big bloat of cheese).

People literally have forgotten to read and embrace the text, everyone wants; YouTube tutorials, or some designed way to make them understand.
Shit, its a no joke, that's why AI have evolved these days.
Make our life easy?  Lol

It can easily fetch content from web and easily showcase the actual content only. If that content is valuable, we should value our way to taking it.

Actually many of you might know famous news reader called *Feedly*, it is based on Rss system under-the-hood.

**** Feed Readers

If you use window there are famous readers like fluent reader.
On Linux you get [[https://newsboat.org/][newsboat]] (terminal lovers), I use [[https://github.com/skeeto/elfeed][elfeed]] (Emacs way).

For GUI Linux user you get : (Install with your system's package manager or use AppImage/Flathub)

  + [[https://github.com/lwindolf/liferea/][Liferea]]
  + [[https://github.com/yang991178/fluent-reader][Fluent-reader]]
  + [[https://www.thunderbird.net/en-US][Thunderbird]] (Email client + Rss)
  + [[https://gitlab.com/news-flash/news_flash_gtk][NewsFlash]]
  + [[https://apps.kde.org/en/akregator][Kde's Akregator]]

Watching YouTube contents is whole lot better in Mpv with sponsorblock (It gives seamless content joy)


Actually elfeed integrates so well with Emacs, I don't have to learn new stuffs for another application or keyboard shortcuts.

That's one of the reason I call *Emacs as the GOAT-E (Editor)*.

I will try to expand more bits on rss feeds value by making a detailed post.
