#+title: Small Prophets
#+date: 2026-10-03
#+tags[]: series review
#+refs[]: prophet

[[https://www.imdb.com/title/tt38504111/][Small Prophets]] is a new Apple TV series of 2026. Its more like a mini movie, which only has =6=
episodes and each runs for 30 mins.

Its a lively & a magical series which is so immersed in small view. You'll just see main character's
jungly house, some neighbors and a super mart store as work place. Just these and 3 unique and tiny
creatures called =Homunculi= which are unlike any other stuff I had seen before.

Its a fresh breather series with unique angle and peaceful take on future prediction and life.

I felt there was light british comedy here, but nothing that was funny. Just a subtle touch of
comedic side during work place conversation and incidents.

You might also want to read IMDB reviews since they also say good words on this series as I felt the
same. Heart warming, refreshing to watch and stirs your soul (maybe).

These kinda series or watch is absolutely required in these days, compared to more noise creating ones.
