#+title: Taxi: the French Franchise
#+date: 2026-10-04
#+tags[]: movies review
#+refs[]: taxi

[[https://en.wikipedia.org/wiki/Taxi_(film_series)][Taxi]] is french movie franchise I discovered by research (🦜). It has amazing comedy and good story.
All 5 movies are almost the same in story, but the fun gets going. Its all about a taxi driver in Marcielle doing his taxi job and there is a very funny police work and chasing criminal.

The "community police" as termed as very funny, especially *Émilien* was the favorite character in
this series and paired along with Gilbert which makes the pair more funnier. And there is racing
taxi car which switches mode and goes on rampage across the city, very fun to see passenger holding
on during the drive. Lol why would they say "hurry up within XY minutes" and regret it after.

- [[https://en.wikipedia.org/wiki/Taxi_(1998_film)][Taxi (1998)]] : The OG movie and introductory of all ventures
- [[https://en.wikipedia.org/wiki/Taxi_2][Taxi 2 (2000)]] : Same same but different
- [[https://en.wikipedia.org/wiki/Taxi_3][taxi 3 (2003)]] : Same again but lets move on
- [[https://en.wikipedia.org/wiki/Taxi_4][Taxi 4 (2007)]] : Same again with more fun
- [[https://en.wikipedia.org/wiki/Taxi_5][Taxi 5 (2018)]] : Kinda a let down, but similar

I'm not linking to IMBD ot TVDB, you can find them out easily with year, but embrace wikipedia and
digest text please.

All 4 sequel has two main character and it gets funnier and funnier, thanks to Emilien and Gilbert.
The fifth kinda is out of way and does not have emilien ;-(, but has another character similar so
kinda is similar.

This stays as one of my favorite comedy along the "Police Academy" in [[file:../media.org][Media]] page
