#+hugo_base_dir: ../
#+hugo_section: memoir
#+OPTIONS: toc:2


* Memoir
** Journey Begins :log:memoir:first:
   :PROPERTIES:
   :EXPORT_FILE_NAME: blogging journey
   :EXPORT_DATE: <2023-03-21 Tue>
   :END:

I have almost set my first static website.
From here my creativity goes public to the world.

Its just a small thing, but my passion thanks me for this.

Its time.. time to begin the chapter!
** Emacs is OP :editors:emacs:neovim:
   :PROPERTIES:
   :EXPORT_FILE_NAME: emacs-goat
   :EXPORT_DATE: 2023-03-22
   :EXPORT_HUGO_DRAFT: false
   :END:

Before anyone shouts vim, let me ~:q!~
I was a vimmer for a year, I played and had a good basic config. Even after an year, I didnt grasp the full potential of vim, its was just handy to use =hjkl= to move around.

But When I learnt Emacs, the experience was immense, it defines how things are meant and the legacy of emacs of 40 years is not a joke.

I cannot just rant to make people ditch vim for emacs, But once you understand you will realize, that is my friend people went and made ~evil~ mode to emulate Vi layer (vim 100%).

Now they get the *Best* of both the World!

Nonetheless, Emacs is the *GOAT* !
