#+hugo_base_dir: ../
#+hugo_section: posts
#+OPTIONS: toc:2

    
* Posts
** Tools that are Best! :cli:linux:minimal:tools:
   :PROPERTIES:
   :EXPORT_FILE_NAME: tools-readme
   :EXPORT_DATE: 2023-03-17
   :EXPORT_HUGO_DRAFT: false
   :END:

--------------

*** Utilities that are Best! 🌟
--------------

|-------------------------+-------------------------------------|
| Class                   | Name                                |
|-------------------------+-------------------------------------|
| Window Manager          | [[https://hyprland.org/][Hyprland]] 🌸                          |
| Text Editor             | [[https://www.gnu.org/software/emacs/][Emacs]] 💮                             |
| Gtk Theme               | [[https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme][Gruvbox]] / [[https://github.com/vinceliuice/Orchis-theme][Orchis]] 🎨                  |
| Font                    | [[https://tosche.net/fonts/comic-code][Comic Code]] / [[https://github.com/dtinth/comic-mono-font][Comic Mono]] / [[https://github.com/tonsky/FiraCode][Fira Code]] |
| Pdf Reader              | [[https://github.com/ahrm/sioyek][Sioyek]] 📔 (ditch zathura)            |
| Media Player            | [[https://mpv.io][MPV!]] 🎬 (its MVP too)                |
| Image Viewer            | [[https://sr.ht/~exec64/imv/][Imv]] 🖼️                               |
| RSS Reader              | [[https://github.com/skeeto/elfeed][Elfeed]] 📰 (Again, Emacs)             |
| Music Player            | [[https://github.com/ncmpcpp/ncmpcpp][Ncmpcpp]] or [[https://github.com//mingus][Mingus in Emacs]] 🎶        |
| Terminal                | [[https://codeberg.org/dnkl/foot][Foot]] via footclient ⚽               |
| Menu/Launcher           | [[https://github.com/Cloudef/bemenu][Bemenu]] 🚀                            |
| Notification            | [[https://github.com/dunst/dunst][Dunst]]  🛎️                            |
| Shell                   | [[https://zsh.org][Zshell]] with [[https://starship.rs][Starship]] 🔰              |
| Status Bar              | [[https://github.com/Alexays/Waybar][Waybar]]  🍥                           |
| Favourite Color-Schemes | Modus-Vivendi + Gruvbox             |
|-------------------------+-------------------------------------|

#+begin_quote
Rest all other stuffs I do in Emacs, tbh I could do everything in Emacs lol.
#+end_quote


Feel free to comment down and ask me doubts or about some improvements, you wanna inform! I will be glad.
** My Linux Journey :distro:linux:
   :PROPERTIES:
   :EXPORT_FILE_NAME: linux-journey
   :EXPORT_DATE: 2023-03-10
   :EXPORT_HUGO_DRAFT: false
   :END:


*Small info/log on my linux journey and my experience.*

/If you are reading this, I encourage you to write blogs like this and have it in your git repo. Don't forget to tag or inform me, I'd be glad to read your journey too!/

-----

*** My Linux Journey

My linux journey was from Linux Mint > EndeavourOS > Arch Linux > and now NixOS.

Tbh I loved LM and Arch alot, I was a devotee to Arch too, and I hated Nix when I tried, cause things were weird.
+ You won't know where to start nor what to refer
+ Flakes or home-manager, How to understand?
+ Do nix-env or rebuild all the time?
+ What files to edit to achieve same setup as my previous distro?

  These were all the things that I hated and was frustrated about, there was still many things that felt hard.
  I did leave Nix and install Arch few times back and forth, I was debating with myself and id my own research all over Internet.

  That is when I thought nix lacked Documentation or good YouTuber to speak of, I really wish one of them could explain and make it their distro to explain timely on things.

  Fine, somehow forced myself and came a long way of setting up Good working nixos config, now I'm on flake

  Nix is great if it works as expected or if we make it work, but, if I get stuck or the issue goes for days that is when I really hate Nix, because it ain't easy to solve some unique issues. Most of these apply for HomeManager actually, it adds more trouble.

  It is adviced to learn how Nix works or Nix as Functional Programming Language.
** Should you try Nixos? :emacs:distro:linux:nixos:
   :PROPERTIES:
   :EXPORT_FILE_NAME: try-nixos
   :EXPORT_DATE: <2023-03-23 Thu>
   :EXPORT_HUGO_DRAFT: false
   :END:

--------------

*** Now if you get doubt of, "Should I try NixOS?" ❄️

Here is an answer from a non-programmer, who just browses and watches media.
Just don't, if you are looking for small benefit. Don't!
You will regret having hard time to figure out petty things, again forget about error, you cannot even search in web.

But, if you have decided, go with it. According to me (non-programmer), these points are good to consider NixOS
 + You use Emacs (lol), *Emacs* ❤️  *Nix* is Match made in Heaven.
 + You want to declare stuffs and get same output, and forget what all you setup, cause its all declared in config.
 + You want an isolated environments (shell) to do some stuffs without involving whole system.
 + You want to stop troubleshooting and breaking update and are lazy to backup, and want to rollback with ease like with just a reboot.
 + You want to say I use *Nixos Btw*.
 + You don't want to worry about breaking your system nor fix something when you are updating system.
 + You are willing to learn (advanced) things and fine with steep learning curve.

--------------
   
*** How I manage my system 🌲

I manage my whole system with single org file. Its easy and pretty handy. You can read that file here *↬* [[https://github.com/idlip/d-nix/blob/onepiece/d-setup.org][d-setup.org]] , its both self documenting and has all source code blocks.

Another key feature in my setup is, every file i tangle is at *read-only mode*. So generally we can avoid editing/touching them. Thus, every action has to be made in *d-setup.org* only.

Also, I have made files to be *symlink*, so i can edit them without requiring to rebuild whole thing!

--------------


**** Credits 🎖️

These configs were the inspiration and helped to build this way.

I thank them sincerely.

[[https://github.com/Iron-Shark/Technonomicon][Iron Shark]] *⟹* Made migrating to Single org-file config very easy.

[[https://github.com/sioodmy/dotfiles][Sioodmy]] *⟹* First config which I understand thoroughly and modified based on this.

------------------------------------------------------------------------------------------

