#+hugo_base_dir: ../
#+hugo_section: snippets
#+OPTIONS: toc:2


* Snippets
** Journey Begins :log:snippets:first:
   :PROPERTIES:
   :EXPORT_FILE_NAME: blogging journey
   :EXPORT_DATE: <2023-03-21 Tue>
   :END:

I have almost set my first static website.
From here my creativity goes public to the world.

Its just a small thing, but my passion thanks me for this.

Its time.. time to begin the chapter!
** Emacs is OP :snippets:editors:emacs:neovim:
   :PROPERTIES:
   :EXPORT_FILE_NAME: emacs-goat
   :EXPORT_DATE: 2023-03-22
   :EXPORT_HUGO_DRAFT: false
   :END:

Before anyone shouts vim, let me ~:q!~
I was a vimmer for a year, I played and had a good basic config. Even after an year, I didnt grasp the full potential of vim, its was just handy to use =hjkl= to move around.

But When I learnt Emacs, the experience was immense, it defines how things are meant and the legacy of emacs of 40 years is not a joke.

I cannot just rant to make people ditch vim for emacs, But once you understand you will realize, that is my friend people went and made ~evil~ mode to emulate Vi layer (vim 100%).

Now they get the *Best* of both the World!

Nonetheless, Emacs is the *GOAT* !
** RSS : The better Internet :snippets:news:internet:read:rss:
:PROPERTIES:
:EXPORT_FILE_NAME: rss-web
:EXPORT_DATE: 2023-03-23
:EXPORT_HUGO_DRAFT: false
:END:

I don't have to say this, the Internet is hella bloated.. Junks are everywhere, nobody knows that they read shit, they are watching shits whole time.

Just do a test, How popup have you closed today, How many cookies have you eaten, How many captchas did you solve, How many minutes did you wait to skip an ad just to watch a video...
/It goes on/.

Rss stands for *Really Simple Syndication*, It is a classic on consuming web as supposedly it was built for. Today its all crappy *javascript* (a big bloat of cheese).

People literally have forgotten to read and embrace the text, everyone wants; youtube tutorials, or some designed way to make them understand.
Shit, its a no joke, thats why AI have evolved it.
Make our life easy?  Lol


It can easily fetch content from web and easily showcase the actual content only. If that content is valuable, we should value our way to taking it.

If you use window there are famous readers like fluet reader.
On Linux you get *newsboat* (terminal lovers), I use *elfeed* (Emacs way).

Actually elfeed integrates so well with Emacs, I dont have to learn new stuffs for another application or keyboard shortcuts.

That's one of the reason to call *Emacs as the GOAT-E (Editor)*.
