#+hugo_base_dir: ../
#+hugo_section: snippets
#+OPTIONS: toc:2


* Snippets
** Journey Begins :log:snippets:first:
   :PROPERTIES:
   :EXPORT_FILE_NAME: blogging journey
   :EXPORT_DATE: <2023-03-21 Tue>
   :END:

I have almost set my first static website.
From here my creativity goes public to the world.

Its just a small thing, but my passion thanks me for this.

Its time.. time to begin the chapter!
** Emacs is OP :snippets:editors:emacs:neovim:
   :PROPERTIES:
   :EXPORT_FILE_NAME: emacs-goat
   :EXPORT_DATE: 2023-03-22
   :EXPORT_HUGO_DRAFT: false
   :END:

Before anyone shouts vim, let me ~:q!~
I was a vimmer for a year, I played and had a good basic config. Even after an year, I didnt grasp the full potential of vim, its was just handy to use =hjkl= to move around.

But When I learnt Emacs, the experience was immense, it defines how things are meant and the legacy of emacs of 40 years is not a joke.

I cannot just rant to make people ditch vim for emacs, But once you understand you will realize, that is my friend people went and made ~evil~ mode to emulate Vi layer (vim 100%).

Now they get the *Best* of both the World!

Nonetheless, Emacs is the *GOAT* !
** RSS : The better Internet :snippets:news:internet:read:rss:
:PROPERTIES:
:EXPORT_FILE_NAME: rss-web
:EXPORT_DATE: 2023-03-23
:EXPORT_HUGO_DRAFT: false
:END:

I don't have to say this, the Internet is hella bloated.. Junks are everywhere, nobody knows that they read shit, they are watching shits whole time.

Just do a test, How popup have you closed today, How many cookies have you eaten, How many captchas did you solve, How many minutes did you wait to skip an ad just to watch a video...
/It goes on/.

Rss stands for *Really Simple Syndication*, It is a classic on consuming web as supposedly it was built for. Today its all crappy *javascript* (a big bloat of cheese).

People literally have forgotten to read and embrace the text, everyone wants; youtube tutorials, or some designed way to make them understand.
Shit, its a no joke, thats why AI have evolved it.
Make our life easy?  Lol


It can easily fetch content from web and easily showcase the actual content only. If that content is valuable, we should value our way to taking it.

If you use window there are famous readers like fluet reader.
On Linux you get *newsboat* (terminal lovers), I use *elfeed* (Emacs way).

Actually elfeed integrates so well with Emacs, I dont have to learn new stuffs for another application or keyboard shortcuts.

That's one of the reason to call *Emacs as the GOAT-E (Editor)*.
** Insightful Quotes :read:snippets:quotes:
:PROPERTIES:
:EXPORT_FILE_NAME: insigh-quotes
:EXPORT_DATE: 2023-03-29
:EXPORT_HUGO_DRAFT: false
:END:

I will be making few snippets on few quotes which impressed me or made me laugh for the day!

Hope so, it is insightful enough for you also.

-------------------


+ Self quote

  #+begin_quote
 Don't just read, Think and Understand!
#+end_quote

+ Walt Kelly

  #+begin_quote
  Every burden is a blessing.
#+end_quote

+ Gustave Flaubert

  #+begin_quote
  The art of writing is the art of discovering what you believe.
#+end_quote

+ Samuel Butlet

  #+begin_quote
  Let us be grateful to the mirror for revealing to us our appearance only.
#+end_quote

+ Joseph Cossman

  #+begin_quote
  Obstacles are things a person sees when he takes his eyes off his goal.
#+end_quote

+ Henny Youngman

  #+begin_quote
  I told the doctor I broke my leg in two places. He told me to quit going to those places.
#+end_quote

+ Barabara Tober

  #+begin_quote
  Traditions are group efforts to keep the unexpected from happening.
#+end_quote

+ Frank Wilczek

  #+begin_quote
In physics, you don't have to go around making trouble for yourself - nature does it for you.
  #+end_quote

+ David Coblitz

  #+begin_quote
  A committee can make a decision that is dumber than any of its members.
#+end_quote


-------------------


#+begin_center
With that *"quoted"*, I hope you have a great day!

Visit the snippets again!
#+end_center
