#+hugo_base_dir: ../
#+hugo_section: snippets
#+OPTIONS: toc:2

* Snippets
** Journey Begins :log:snippets:first:
   :PROPERTIES:
   :EXPORT_FILE_NAME: blogging journey
   :EXPORT_DATE: <2023-03-21 Tue>
   :END:

I have almost set my first static website.
From here my creativity goes public to the world.

Its just a small thing, but my passion thanks me for this.

Its time.. time to begin the chapter!
** Emacs is OP :snippets:editors:emacs:neovim:
   :PROPERTIES:
   :EXPORT_FILE_NAME: emacs-goat
   :EXPORT_DATE: 2023-03-22
   :EXPORT_HUGO_DRAFT: false
   :END:

Before anyone shouts vim, let me ~:q!~
I was a vimmer for a year, I played and had a good basic config. Even after an year, I didn't grasp the full potential of vim, it was just handy to use =hjkl= to move around.

But When I'm learning Emacs, the experience is immense, it defines how things are meant and the legacy of Emacs for 40 years, is not a joke.

I cannot just rant to make people ditch vim for Emacs, But once you understand you will realize, that is why people went and made ~evil~ mode to emulate Vi layer (vim 100%).

Now they get the *Best* of both the World!

Nonetheless, Emacs is the *GOAT* !
** RSS: The better Internet :snippets:news:internet:read:rss:
:PROPERTIES:
:EXPORT_FILE_NAME: rss-web
:EXPORT_DATE: 2023-03-23
:EXPORT_HUGO_DRAFT: false
:END:

*** Cheesy Internet

I don't have to say this, the Internet is hella bloated.. Junks are everywhere, nobody knows that they read shit, they are watching shits whole time.

Just do a test, How many popups have you closed today, How many cookies (web) have you eaten, How many captchas did you solve, How many minutes did you wait to skip an ad just to watch a video... Even worse, ads sponsors are embedded within a video (So cruel and harsh world)
/It goes on/.

Internet and digital software's are getting so much bloated, people (normies) have forgotten Unix or say 'minimalism'. People are upgrading RAM like anything, 8GB ain't enough it-seems for them. Here, I do everything with just 4GB RAM.
People these days all need ready-made/ready-to-work  stuffs, I wonder how do they even watch DIY channels on YouTube.

*** The Hero

Rss stands for *Really Simple Syndication*, It is a classic on consuming web as supposedly it was built for. Today its all crappy *JavaScript* (a big bloat of cheese).

People literally have forgotten to read and embrace the text, everyone wants; YouTube tutorials, or some designed way to make them understand.
Shit, its a no joke, that's why AI have evolved these days.
Make our life easy?  Lol

It can easily fetch content from web and easily showcase the actual content only. If that content is valuable, we should value our way to taking it.

Actually many of you might know famous news reader called *Feedly*, it is based on Rss system under-the-hood.

**** Feed Readers

If you use window there are famous readers like fluent reader.
On Linux you get [[https://newsboat.org/][newsboat]] (terminal lovers), I use [[https://github.com/skeeto/elfeed][elfeed]] (Emacs way).

For GUI Linux user you get : (Install with your system's package manager or use AppImage/Flathub)

  + [[https://github.com/lwindolf/liferea/][Liferea]]
  + [[https://github.com/yang991178/fluent-reader][Fluent-reader]]
  + [[https://www.thunderbird.net/en-US][Thunderbird]] (Email client + Rss)
  + [[https://gitlab.com/news-flash/news_flash_gtk][NewsFlash]]
  + [[https://apps.kde.org/en/akregator][Kde's Akregator]]

Watching YouTube contents is whole lot better in Mpv with sponsorblock (It gives seamless content joy)


Actually elfeed integrates so well with Emacs, I don't have to learn new stuffs for another application or keyboard shortcuts.

That's one of the reason I call *Emacs as the GOAT-E (Editor)*.

I will try to expand more bits on rss feeds value by making a detailed post.
** Insightful Quotes :snippets:quotes:
:PROPERTIES:
:EXPORT_FILE_NAME: insight-quotes
:EXPORT_DATE: 2023-03-29
:EXPORT_HUGO_DRAFT: false
:END:

I will be making few snippets on few quotes which impressed me or made me laugh for the day!

Hope so, it is insightful enough for you also.

-------------------


+ Self quote

  #+begin_quote
 Don't just read, Think - Research and Understand!
#+end_quote

+ Walt Kelly

  #+begin_quote
  Every burden is a blessing.
#+end_quote

+ Gustave Flaubert

  #+begin_quote
  The art of writing is the art of discovering what you believe.
#+end_quote

+ Samuel Butlet

  #+begin_quote
  Let us be grateful to the mirror for revealing to us our appearance only.
#+end_quote

+ Joseph Cossman

  #+begin_quote
  Obstacles are things a person sees when he takes his eyes off his goal.
#+end_quote

+ Henny Youngman

  #+begin_quote
  I told the doctor I broke my leg in two places. He told me to quit going to those places.
#+end_quote

+ Barabara Tober

  #+begin_quote
  Traditions are group efforts to keep the unexpected from happening.
#+end_quote

+ Frank Wilczek

  #+begin_quote
In physics, you don't have to go around making trouble for yourself - nature does it for you.
  #+end_quote

+ David Coblitz

  #+begin_quote
  A committee can make a decision that is dumber than any of its members.
#+end_quote


-------------------


#+begin_center
With that *"quoted"*, I hope you have a great day!

Visit the snippets again!
#+end_center
** Cognizance :snippets:quotes:
:PROPERTIES:
:EXPORT_FILE_NAME: cognizance-quotes
:EXPORT_DATE: 2023-04-22
:EXPORT_HUGO_DRAFT: false
:END:
Welcome to next snippet of Quotes.

Hope so, it is advising enough to make your day well ;)

------

+ Psychology Reads

#+begin_quote
People Aren't Better Lie Detectors (50-60%) in More Realistic Settings
#+end_quote

#+begin_quote
Nothing in life is as important as you think it is, while you are thinking about it
#+end_quote

+ Herm Albright

  #+begin_quote
A positive attitude may not solve all your problems, but it will annoy enough people to make it worth the effort.
#+end_quote

+ Bret Harte

  #+begin_quote
The only sure thing about luck is that it will change.
#+end_quote

+ Philip G. Hammerton

  #+begin_quote
Have you ever observed that we pay much more attention to a wise passage when it is quoted than when we read it in the original author?
#+end_quote

+ Woodrow Wilson

  #+begin_quote
The man who is swimming against the stream knows the strength of it.
#+end_quote


------

#+begin_center
With these sweet little pies, I hope it does make your day alive ;)
#+end_center
** Beyond Ken :quotes:snippets:
:PROPERTIES:
:EXPORT_FILE_NAME: ken-quotes
:EXPORT_DATE: 2023-06-02
:EXPORT_HUGO_DRAFT: false
:END:

Welcome to some more snippet of Quotes.
Lately I have been busy, kinda dusting off my table. /Ooof.. procastination!/

Some more laughs, some more values!
------

+ Napoleon Bonaparte

  #+begin_quote
If you want a thing done well, do it yourself.
  #+end_quote

+ Henny Youngman

  #+begin_quote
I once wanted to become an atheist, but I gave up - they have no holidays.
  #+end_quote

+ Lillian Hellman

  #+begin_quote
Things start out as hopes and end up as habits.
  #+end_quote

+ Dorothy Parker

  #+begin_quote
The cure for boredom is curiosity. There is no cure for curiosity.
  #+end_quote

+ Randy K. Milholland

  #+begin_quote
Lies are like children. If you don't nurture them, they'll never be useful later.
  #+end_quote

+ Ralph W. Sockman

  #+begin_quote
The test of courage comes when we are in the minority. The test of tolerance comes when we are in
 the majority.
  #+end_quote

+ Ethel Waters

  #+begin_quote
We are all gifted. That is our inheritance.
#+end_quote

+ Tom Brokaw

  #+begin_quote
It's easy to make a buck. It's a lot tougher to make a difference."
#+end_quote

+ Sonya Parker

  #+begin_quote
Live your life for you not for anyone else. Don’t let the fear of being judged, rejected or
 disliked stop you from being yourself.
#+end_quote

+ Wayne Dyer

  #+begin_quote
If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see
 obstacles.
#+end_quote

+ Anime

  #+begin_quote
The strongest hearts have the most scars.
#+end_quote

-----------

#+begin_center
Hopefully with those melifluous thoughts, I hope you are alright ;)
#+end_center
** Organize File :snippets:orgmode:
:PROPERTIES:
:EXPORT_FILE_NAME: organize-file
:EXPORT_DATE: 2023-12-16
:EXPORT_HUGO_DRAFT: false
:END:

From past few days I have been dabbling in the dimension of how to organize files, notes in effective manner. After jumping deep into the rabbit hole, I went on a spree of digesting several blog posts, articles on maintaining files, organizing notes, getting things done, what not, the list goes on.

With power of *org-mode* comes the doubt, is it efficient to maintain one big org file or multiple small files. Yes, its personal preference based on users need, there is no set guided rules.

I stumbled across =Zettelkasten= system which wasn't new, I was aware of it in the likes of =org-roam=, although I believe I did not have much matter to use it to some potential to form sensible network. So for now, no hard plans of multiple small files.

After many reading, especially Karl voit's posts ([[https://karl-voit.at][site]]), I was kinda convinced that file system hierarchy does not make sense, as the file system model I have may change over time, and I would not like to remember and know where I placed something and where to place something. The schema of Zettelkasten is also against this, like you maintain small files and just connect them based on UniqueID or with complexity of SQL database. The simpler alternative would be =denote= emacs package, then too I don't see the light on using it to the potential. I liked denote way of naming files, and it is format agnostic, does not depend on anything. Just pure elisp to do the job.

Thus as a safer approach, I renamed some notes files to denote convention (as there is no harm/changes in that).

Ultimately the fruit to yield is, just go with whatever is easy and that gets the work done. Forgetting people's upfront images, looking at other side proved me that nobody is well organized in every way. Everybody lacks something in one or the other way, like I saw person who maintained file system well organized, but the desk and the room was gross and jam packed. So it depends, but the key takeaway is, if it just works; That's enough. But as time goes, changes and upgrades are required.
