#+title: Replenish theme - its Emacsy
#+date: [2026-03-19 Thu]
#+tags[]: emacs orgmode

With previous post on [[/posts/revamp-blog-2026][revamp my blogs]], I finally today went ahead and upgrades the beautiful [[https://github.com/ArthurHeymans/hugo-emacs-theme/][emacs theme made by Arthur]], and locally forked to add goodies.

Reflecting on upgrades since beginning it has received, I'm strictly thinking to settle with this, as it looks good, minimal enough and modern looking, adaptive in mobile, has rss support and I can extend as I want and more than all, I can live in my editor - =Emacs=.

Initially the itch to setup own blog and personal website starting with [[https://rudra.dev/][rudra.dev]] (may no longer be active) site which had simple blog listing made using Hugo. Then I moved to org-mode's =org-publish=, and had setup replacing the same with full html and css from org. I still have the theme in another branch [[https://github.com/idlip/idlip.github.io/tree/voyage][here]]. But again wanted to extend things and org-publish did not feel clean. So went back to hugo, was exploring plethora of theme and went ahead with [[https://gitlab.com/rmaguiar/hugo-theme-color-your-world][Color your world]], which looked unique giving color accent for whole page and letting user pick with choice. It had search and katex support, but later realized I dont use any of it and it loaded many JS files. Then began another hunt and was thinking of [[https://github.com/Livour/hugo-mana-theme][Mana theme]], which seemed cool and was active in development with new features every commit.

Right at this time, magically the [[https://www.reddit.com/r/emacs/comments/1qtvnpl/making_my_blog_look_and_feel_like_emacs/][Emacs theme came by reddit]] and the path got clear and jumped the ship.

Enough of history, today I added some improvements to this theme in my fork and hopefully I'll be doing more blogs here with as much information I can spread.
I've been enjoying reading Light novels - Apothecary Diaries and Ascendance of Bookworm, and skimming hacker news and blog posts from [[https://www.feedbase.org/][feedbase]], hence its time to give back and share as well.

----

#+begin_center
/Its not always of what you can consume, can be what you give as well./
#+end_center
