#+title: OBTF as Second Brain with Org mode
#+date: 2025-09-06
#+tags[]: orgmode emacs pkm
#+draft: false


*One Big Text File* is simply writing down mostly everything in single file to organize or manage data. This single file acts as the source of knowledge and holds all notes.

Second brain has been a buzz word, thanks to the sourcing of Zettelkasten method, every productivity freak is on the stance to organize their life and get things done.

But I soon came to the conclusion by reading many blogs and reddit discussions that, searching is far superior than organizing. On internet all we do is search for information, and not organize or build system just to get info. This is how note taking should work as well. Just for *efficient retrieval and storage*. 

Thanks to my introduction to emacs and getting deep into rabbit hole, Org mode has been the great tool to handle plain text file as an Organization platform. Just like emacs (OS), Org mode can also be extended to endless limit (I dare say it). If emacs is OS, Org mode is for me Init system (systemd).

You can read more about my note taking journey in [[id:emacs-msc][this post]].

This context is also written in favor to post it on r/obtf

* Org mode is the best tool for managing OBTF
Many popular workflow would go by simple format as bullet points with Time date and info, and regexp based searching via CLI (rg, vim, grep, sed.... bash scripts)

Org mode has many bells and whistles (features) that aid in this method. Tags, integration with commands and rich source of documentation (one of the best things of Emacs or org mode). Thanks to emacs and [[https://protesilaos.com/][protesilaos stavrou]] I learnt how important are documentation and writing sensible notes. It means alot for future self to recognize and re-instantiate the thoughts and state.

Org mode has an =datetree= method which has file heading hierarchy in the Year > Month > Day and 4th nested heading follows any notes.

#+begin_src org
  ,* 2022
  ,** 2022-10 October
  ,*** 2022-10-07 Friday
  ,*** 2022-10-08 Saturday
  ,**** <Any notes I'm capturing>            :tag1:tag2:
#+end_src

This gives out the leverage of journaling, but also a lazy man's organization. I use tagging extensively to most of the (4th) heading based on context so as to narrow down to filter.

#+begin_src org
  # learning notes --- l@
  ,#+tags: l@coding l@emacs l@bioinfo l@nix l@bash l@julia l@rstats l@python l@devnote l@latex l@til

  # generic notes to remember or readme --- n@
  ,#+tags: n@linux n@shell n@cli n@book n@idea

  # projects --- p@
  ,#+tags: p@webcli p@cyanate p@scitomep
#+end_src

- These tag help to categorize the heading in some (lazy) way

Org mode has =org-sparse-tree= bound to =C-c /= which helps to narrow down based on tag or property. Also another emacs package =consult= helps to take it up further via =consult-line= and =consult-org-heading= along with =org-ql= package. Org mode also has =#+select_tags= to export headings to file.

#+begin_src org
  ,#+select_tags: r@book
#+end_src

With that we can =C-c C-e= (org-export-dispatch) and press "O O" (make sure org is in org-export-backends) to get temporary Org buffer only with those heading.
This logically acts as an individual file with that tag/category, thus being atomic in my sense. Org-sparse-tree might also be same.

----

* Key takeaways

whatever the system or the tool is, the main takeaways every resource provides is to review the notes and write it for future self. Every capture is to review back and make the fleeting note into and rich information.
This OBTF with org mode satisfies that needs given that user reviews the notes and visits back to digest it again.