#+title: Overview of Decentralized socials
#+tags[]: snippets
#+draft: false

- https://arxiv.org/abs/2504.00071

The paper elaborates on architecture of Decentralized social networks.
Although not much takeaways for common users, but it ensure that Decentralized networks would be the way future for privacy and security concerns.

Although I lurk around mastodon, I think Decentralized did not work as expected. Althought small communities can group together, the inter-connection between other serves are tedious.
There is no smoother discovery of posts. The pain is, some account in a server must expose or connect with other server people to get their feed/posts exposed in current server. So unless that, even with trendy hashtags, there is no way to view their posts.

This becomes a hindrance, that's why bluesky with their big mono server can tackle them with some business model.
Although mastodon has =mastodon.social= instance for big giant network.

Even though small communities thrive, a single person cannot take forth maintenance longer, many would appreciate some volunteer donation and support.

As a sad one, =emacs.ch= got shutdown due to its maintenance burder. As of writing =emacs.social= seems to be up for same cause, although the emacs community has already diversed.

-------
Also this hopefully marks end of an hiatus to this site, and revert this blog site with more stream of posts.