#+title: Revamp the blogs
#+date: 2026-01-06
#+tags[]: snippets
#+draft: false


Hello world, again!

Hopefully with this new year (2026) I wish to do regular blogs and get habit of giving (writing) out more.

I'm a heck fanatic of ASCII text, I prefer text reading over any media. I really want to get on with blog (even crap quality is fine for now). I actually write tech-report for [[https://fossunited.org/blogs/tech-report][FOSSUnited platform]] and to improvise that as well I better do more writing here!

Btw with this new year I bought a domain for myself (https://idlip.in) yay :), been thinking for many days and finally went ahead. Might do zororg.in or dev as well.

The name is mostly derived as my github username, the significance is simply first two letter transposed of my name.
Dilip (idlip)
If not for this, maybe I'd have picked "Gol D. Lip" in the veins of OnePiece (Gol D. Roger) {hey there is will of D here}

You can send me email on [[mailto:hi@idlip.in][hi@idlip.in]] (I love emails as well)

/Read more, write more, give more/