#+title: TIL a word: Sentience
#+date: 2026-08-01
#+tags[]: til mosaic sciencesante meetup

- NGL, Its a subtle word among =Sentence= and =Patience=

I attended the [[https://mosaichq.org/events/science-sante-blr-3-1-aug-2026/][third science sante]] (my 2nd sante) and I was excited to attend because there will be
[[https://en.wikipedia.org/wiki/Unconference#:~:text=the%20agenda%20is%20created%20by%20the%20attendees%20at%20the%20beginning%20of%20the%20meeting%2E%20Anyone%20who%20wants%20to%20initiate%20a%20discussion%20on%20a%20topic%20can%20claim%20a%20time%20and%20a%20space][*Unconference* session]] during the meetup (TBH I only cared for that & of course the free Lunch -
_Nothing's better than free food_!).

Thankfully this event is not equipped with only talks, I hate the boring talks and presentations
(that's another topic to blog about). [[https://en.wikipedia.org/wiki/Unconference#:~:text=the%20agenda%20is%20created%20by%20the%20attendees%20at%20the%20beginning%20of%20the%20meeting%2E%20Anyone%20who%20wants%20to%20initiate%20a%20discussion%20on%20a%20topic%20can%20claim%20a%20time%20and%20a%20space][Unconference session]] is where group of attendees propose
topics in chits and organizers pick and give space and time to talk about it. And people can
randomly pick any of their interest, sit, listen or speak about it.

These are run in a faith that not only one person speaks or lectures, and its about who you are or
what you are, its more of, here's the topic and lets put our facts and opinions with evidence and
discussion in multi-disciplinary to comment on the matter. But TBH not every topic were ideal, of
course many table go on with one person driving & streamlining the conversation and many putting up
opinions or their own belief. But nonetheless it can turn out to be fruitful session and some
discussion can carry to connect a missing dot.

Just like that on second unconf topic, there was topic on "*Our unsung heroes of Agriculture*".
Immediately as I read the immediate picture I had was of farmer's pets, the soil bacteria, worms,
insects and cattle's, but mostly I thought of micro-organisms (such a small bookish brain I've to
imagine them).

But the proposer's viewpoint were completely different, since the theme of the event was on "Food
Science", they cam right on track with the topic IMO. The person opened the discussion with putting
out the word -> *Sentience*

Sentience means to perceive and sense the feelings of either oneself or others. OP asked that why
don't we human feel sentience among the primary animals that we use for either farming or even as
food. Here they primarily meant _meat_, people consuming them in mass and even farmers utilizing them
in mass. OP wanted to either know why we human are not really feeling sentience towards them or why
do we even not understand that they also have awareness and feelings, why don't we respect those
animals?

Even I sat and argued that we humans might have normalized this based on mapping out, these animals
life cycle is this, purpose is of a sort and we can efficiently utilize them this way.
This was my argument saying that maybe scientist might have already studied them all, and just chose
whats most economical and ideal way for even that species to live? Better to ask a Animal behaviorist TBH.

Others argued that we humans are not welcoming to other humans, it might be our psychology and
*Anthropomorphism*. But at the end, the point did not go anywhere, nobody got answer nor OP was even
contempt (I guess). OP was not definitely looking for these opinions or answers, but I felt like
that was a nice moment to appreciate others lives and think in other animal's shoe (if they wear),
and yes sentience can make us _Buddha_ in some way TBH.

Oof.. it was a coaster for me, initially I thought the topic was on appreciating important of
microbes in farming/agricultural needs (how silly of me..) and then topic shifted on generic
sentience on animals around us, and later I realized that OP was vegan and all they meant was on
Meat consumption (holy... that concludes).

Most bizarre moment was that, just after this unconf, the talk was presented on "Insects as our
future protein food". Appetizing for sure just before lunch!

It's always worthwhile to pause and reflect on the lives of other beings, to recognize the natural behaviors of animals, appreciate their place in the world, and cultivate gratitude for both the joys and hardships we experience. Yet, in the rush of our own lives, we're often too consumed by work, deadlines, and an ever-growing list of tasks to even reflect on ourselves, let alone extend that empathy to other sentient human. Perhaps taking a moment to acknowledge their lives is also a reminder to slow down and reconnect with our own humanity.

# Local Variables:
# jinx-local-words: "sante unconf"
# End:
