#+title: Manga: Three days of happiness
#+date: 2025-02-21
#+tags[]: manga novel
#+draft: false


A light novel by the name, and manga goes by name *Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de* by Sugaru Miaki. His all novels follow similar theme.

#+begin_quote
If you wonder why japanese manga names are reallyyy long, they say that, its useful for buyers to know the gist of what it is about. So basically the names would indicate most of the main theme or gist. It makes sense as it can gives mini-overview on itself.
#+end_quote

The story is kinda depressing, or lets say it makes you sober. More of its an thought provoking story and makes you wonder the importance in life. Although everyone cannot relate based on NEET character, since IRL we are busy with connections and responsibilities and some flow is going on with out life.

This manga/LN left me with lots of questions and lots of thoughts. Wonderful depiction of love, life and the worthwhile of doing things.
In fact, last (extra) chapter was so valuable that gave another perspective of living.

Lot of take in, but many were indirectly spoken. The focus might seem on lifespan, love and death. But the key takeaway would be on passion, interests and career.

Socializing came a bit and flew away, but still seemed positive.

This might be my beginning for loving these kinda manga, of understanding life and maybe kick start reading light novels.

=Good for nothing= was the main theme, but it depicts that it vanishes when loved ones are together.

First time I did not feel much, but reading some pages again felt more pain. After reading this one, I went on searching similar one just like this, but unfortunately nothing like this. This feels different unlike any for me.
I wish I could have started off with light novel, but maybe pictures only gave me more value and more comprehension.
