name = "Haki"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "A hugo theme for dark watchers"
homepage = "https://github.com/idlip"
tags = ["blog", "plain", "starter", "development"]
features = ["blog"]
min_version = "0.1"

[author]
  name = "idlip"
  homepage = "https://github.com/idlip"
