name: org-publish

on:
  push:
    branches:
      - voyage # branch to use
jobs:
  org-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes
        # tui version for simplicity
      - name: Build the site
        run: ./build.sh # run emacs script to build

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages # deploy to branch
          folder: public # the built directory to deploy
